# Competence Center - itenium
#
# Site settings
# Access in templates via {{ site.myvariable }}.

title: Competence Center - itenium
email: info@itenium.be
jobsEmail: jobs@itenium.be

baseurl: "/Competence-Center"
url: "https://itenium.be"


twitter_username: itenium_be
github_username:  itenium-be
linkedIn_username: itenium
instagram_usname: itenium
