# Competence Center - itenium
#
# Site settings
# Access in templates via {{ site.myvariable }}.

title: Competence Center - itenium
email: info@itenium.be
description: >-
  The itenium Competence Centers. Our tech sessions and
  different tracks including our hands-on workshops and
  lectures as well as our full day bootcamps.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://itenium.be"


twitter_username: itenium_be
github_username:  itenium-be
linkedIn_username: itenium
instagram_usname: itenium
