# Competence Center - itenium
#
# Site settings
# Access in templates via {{ site.myvariable }}.

title: Competence Center - itenium
email: info@itenium.be
jobsEmail: jobs@itenium.be

baseurl: "/Competence-Center"
url: "https://itenium.be"

google_analytics: G-83ZGT364P4

twitter: https://twitter.com/itenium_be
github:  https://github.com/itenium-be
linkedIn: https://be.linkedin.com/company/itenium
instagram: https://www.instagram.com/itenium/
facebook: itenium.be
youtube: "@iteniumconsultancy"
